ProjetoEscolar/Controllers/EscolaController.cs
using MySql.Data.MySqlClient;
using ProjetoEscolar.Dados;
using ProjetoEscolar.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace ProjetoEscolar.Controllers
{
    public class EscolaController : Controller
    {
        // GET: Escola
        public void CarregaAlunos()
        {
            List<SelectListItem> alunos = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=bdEscola;User=root;pwd=12@Teste"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select codAluno, nomeAluno from tbAluno;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    alunos.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();

                con.Open();


            }

            ViewBag.alunos = new SelectList(alunos, "Value", "Text");
        }

        public void CarregaDisciplina()
        {
            List<SelectListItem> disciplina = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=bdEscola;User=root;pwd=12@Teste"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select codDisciplina, Disciplina from tbDisciplina;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    disciplina.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();

                con.Open();


            }

            ViewBag.disciplina = new SelectList(disciplina, "Value", "Text");
        }

        public void CarregaProfessor()
        {
            List<SelectListItem> professores = new List<SelectListItem>();

            using (MySqlConnection con = new MySqlConnection("Server=localhost;DataBase=bdEscola;User=root;pwd=12@Teste"))
            {
                con.Open();
                MySqlCommand cmd = new MySqlCommand("select * from tbProfessor;", con);
                MySqlDataReader rdr = cmd.ExecuteReader();

                while (rdr.Read())
                {
                    professores.Add(new SelectListItem
                    {
                        Text = rdr[1].ToString(),
                        Value = rdr[0].ToString()
                    });
                }
                con.Close();

                con.Open();


            }

            ViewBag.professores = new SelectList(professores, "Value", "Text");
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Escolar()
        {
            return View();
        }
        public ActionResult CadAluno()
        {
            return View();
        }
        Aluno modAluno = new Aluno();
        AcAluno acAlu = new AcAluno();
        [HttpPost]
        public ActionResult CadAluno(FormCollection frm)
        {
            modAluno.nomeAluno = frm["txtNmAluno"];
            modAluno.telAluno = frm["txtTelefone"];
            acAlu.inserirAluno(modAluno);
            ViewBag.Mensagem = "Cadastro Efetuado Com Sucesso";
            return View();
        }

        public ActionResult CadProfessor()
        {
            return View();
        }
        Professor modProf = new Professor();
        AcProfessor acProf = new AcProfessor();
        [HttpPost]
        public ActionResult CadProfessor(FormCollection frm)
        {
            modProf.nomeProf = frm["txtNmProfessor"];
            acProf.inserirProfessor(modProf);
            ViewBag.Mensagem = "Cadastro Efetuado Com Sucesso";
            return View();
        }

        public ActionResult CadNota()
        {
            CarregaAlunos();
            CarregaProfessor();
            CarregaDisciplina();
            return View();
        }

        Nota modNota = new Nota();
        AcNota nota = new AcNota();
        [HttpPost]
        public ActionResult CadNota(Nota modNota)
        {
            CarregaAlunos();
            CarregaProfessor();
            CarregaDisciplina();
            modNota.codProf = Request["professores"];
            modNota.codAluno = Request["alunos"];
            modNota.codDisciplina = Request["disciplina"];

            nota.inserirNota(modNota);
            ViewBag.Mensagem = "Cadastro efetuado com sucesso!";
            return View();
        }



        public ActionResult AtNomeAluno()
        {
            CarregaAlunos();
            return View();
        }
       
        [HttpPost]
        public ActionResult AtNomeAluno(FormCollection frm)
        {
            CarregaAlunos();

            modAluno.codAluno = Request["alunos"];
            modAluno.nomeAluno = Request["txtNomeAluno"];

            acAlu.AtualizarNomeAluno(modAluno);
            ViewBag.atualizar = "Nome Atualizados Com Sucesso!";

            return View();
        }
        public ActionResult AtNomeProf()
        {
            CarregaProfessor();
            return View();
        }

        [HttpPost]
        public ActionResult AtNomeProf(FormCollection frm)
        {
            CarregaProfessor();

            modProf.codProf = Request["professores"];
            modProf.nomeProf = Request["txtNomeProf"];

            acProf.AtualizarNomeProfessor(modProf);
            ViewBag.atualizar = "Nome Atualizados Com Sucesso!";

            return View();
        }

        public ActionResult AtTelAluno()
        {
            CarregaAlunos();
            return View();
        }

        [HttpPost]
        public ActionResult AtTelAluno(FormCollection frm)
        {
            CarregaAlunos();

            modAluno.codAluno = Request["alunos"];
            modAluno.telAluno = Request["txtTelAluno"];

            acAlu.AtualizarTelAluno(modAluno);
            ViewBag.atualizar = "Telefone Atualizado Com Sucesso!";

            return View();
        }

        public ActionResult ConsultaAluno()

        {

            AcAluno acAlu  = new AcAluno();

            GridView dgv = new GridView(); // Instância para a tabela 

            dgv.DataSource = acAlu.consultaAlu(); //Atribuir ao grid o resultado da consulta 

            dgv.DataBind(); //Confirmação do Grid 

            StringWriter sw = new StringWriter(); //Comando para construção do Grid na tela 

            HtmlTextWriter htw = new HtmlTextWriter(sw); //Comando para construção do Grid na tela 

            dgv.RenderControl(htw); //Comando para construção do Grid na tela 

            ViewBag.GridViewString = sw.ToString(); //Comando para construção do Grid na tela 

            return View();

        }

        public ActionResult ConsultaProf()

        {

            AcProfessor acProf = new AcProfessor();

            GridView dgv = new GridView(); // Instância para a tabela 

            dgv.DataSource = acProf.consultaProf(); //Atribuir ao grid o resultado da consulta 

            dgv.DataBind(); //Confirmação do Grid 

            StringWriter sw = new StringWriter(); //Comando para construção do Grid na tela 

            HtmlTextWriter htw = new HtmlTextWriter(sw); //Comando para construção do Grid na tela 

            dgv.RenderControl(htw); //Comando para construção do Grid na tela 

            ViewBag.GridViewString = sw.ToString(); //Comando para construção do Grid na tela 

            return View();

        }
    }
}

ProjetoEscolar/Views/Escola/AtNomeAluno.cshtml
@{
    ViewBag.Title = "AtNomeAluno";
}

<h2>Atualizar Nome do Aluno</h2>

@using (Html.BeginForm("AtNomeAluno", "Escola", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    <h4>Escolha o Aluno que Deseja Atualizar:</h4>
    @Html.DropDownList("alunos", "Escolha o Aluno")
    <br />
    <br />
    <br />
    <h4>Digite o novo nome:</h4>
    <input type="text" name="txtNomeAluno" />
    <br />
    <br />

    <br />
    <input type="submit" value="Atualizar" />
    <br />
    <br />
}
@ViewBag.atualizar 

ProjetoEscolar/Views/Escola/AtNomeProf.cshtml
@{
    ViewBag.Title = "AtNomeProf";
}

<h2>Atualizar Nome do Professor</h2>

@using (Html.BeginForm("AtNomeProf", "Escola", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    <h4>Escolha o Aluno que Deseja Atualizar:</h4>
    @Html.DropDownList("professores", "Escolha o Professor")
    <br />
    <br />
    <br />
    <h4>Digite o novo nome:</h4>
    <input type="text" name="txtNomeProf" />
    <br />
    <br />

    <br />
    <input type="submit" value="Atualizar" />
    <br />
    <br />
}
@ViewBag.atualizar 

ProjetoEscolar/Views/Escola/AtTelAluno.cshtml
@{
    ViewBag.Title = "AtTelAluno";
}

<h2>Atualizar Telefone do Aluno</h2>

@using (Html.BeginForm("AtTelAluno", "Escola", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <br />
    <h4>Escolha o Aluno que Deseja Atualizar:</h4>
    @Html.DropDownList("alunos", "Escolha o Aluno")
    <br />
    <br />
    <br />
    <h4>Digite o novo Telefone:</h4>
    <input type="text" name="txtTelAluno" />
    <br />
    <br />

    <br />
    <input type="submit" value="Atualizar" />
    <br />
    <br />
}
@ViewBag.atualizar 

ProjetoEscolar/Views/Escola/CadAluno.cshtml
@{
    ViewBag.Title = "CadAluno";
}

<h2>Cadastro de Aluno</h2>
@using (Html.BeginForm("CadAluno", "Escola", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <label>Nome do Aluno</label>
    <br />
    <input type="text" id="txtNmAluno" name="txtNmAluno" />
    <br />
    <br />
    <label>Telefone do Aluno</label>
    <br />
    <input type="text" id="txtTelefone" name="txtTelefone" />
    <br />
    <br />




    <br />
    <input type="submit" value="Cadastrar" />
}

ProjetoEscolar/Views/Escola/CadNota.cshtml
@model ProjetoEscolar.Models.Nota

@{
    ViewBag.Title = "Questionario";

    List<string> TipoNotas = new List<string>();

    TipoNotas.Add("MB");

    TipoNotas.Add("B");

    TipoNotas.Add("R");

    TipoNotas.Add("I");

}


<h2>CadNota</h2>

@using (Html.BeginForm("CadNota", "Escola", FormMethod.Post, new { enctype = "multipart/form-data" }))
 {

    @Html.DropDownList("professores", "Escolha o professor")
    <br />
    <br />


    @Html.DropDownList("alunos", "Escolha o Aluno")
    <br />
    <br />


    @Html.DropDownList("disciplina", "Escolha a disciplina")
    <br />
    <br />

    @Html.DropDownListFor(m => m.nota, new MultiSelectList(TipoNotas))

    <input type="submit" value="Cadastrar" />

 }

ProjetoEscolar/Views/Escola/CadProfessor.cshtml
@{
    ViewBag.Title = "CadProfessor";
}

<h2>Cadastro de Professor</h2>

@using (Html.BeginForm("CadProfessor", "Escola", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <label>Nome do Professor</label>
    <br />
    <input type="text" id="txtNmAluno" name="txtNmProfessor" />
    <br />
    <br />
    




    <br />
    <input type="submit" value="Cadastrar" />
}

ProjetoEscolar/Views/Escola/ConsultaAluno.cshtml
@{
    ViewBag.Title = "ConsultaAluno";
}

<h2>Consultar Aluno</h2>

@Html.Raw(ViewBag.GridViewString) 

ProjetoEscolar/Views/Escola/ConsultaProf.cshtml
@{
    ViewBag.Title = "ConsultaProf";
}

<h2>Consultar Professores</h2>

@Html.Raw(ViewBag.GridViewString) 

ProjetoEscolar/Views/Escola/Escolar.cshtml
@{
    ViewBag.Title = "Área do administrador";
}

<h2>Área do administrador</h2>

@Html.ActionLink("Cadastro do Aluno", "CadAluno", "Escola")
<br />
@Html.ActionLink("Cadastro do Professor", "CadProfessor", "Escola")
<br />
@Html.ActionLink("Atualizar Nome do Aluno", "AtNomeAluno", "Escola")
<br />
@Html.ActionLink("Atualizar Telefone do Aluno", "AtTelAluno", "Escola")
<br />
@Html.ActionLink("Atualizar Nome do Professor", "AtNomeProf", "Escola")
<br />
@Html.ActionLink("Consultar Alunos", "ConsultaAluno", "Escola")
<br />
@Html.ActionLink("Consultar Professores", "ConsultaProf", "Escola")
<br/>
@Html.ActionLink("Cadastrar Notas", "CadNota", "Escola")